esphome:
  name: perefn-1-2

esp32:
  board: esp32-c3-devkitm-1
  framework: { type: esp-idf }

external_components: [{source: {type: local, path: custom_components}}]
wifi: { ssid: "Your_WiFi", password: "Password" }

esphome:
  on_boot:
    priority: 200.0
    then: [- lambda: 'wifi::global_wifi_component->stop();']

can:
  id: my_can_bus
  pin: GPIO5

switch:
  - platform: can
    id: relay_1
    bind_to: wall_button
    on_turn_on:  [- gpio.digital_write: { pin: GPIO4, value: high }]
    on_turn_off: [- gpio.digital_write: { pin: GPIO4, value: low }]

gpio: [- { pin: GPIO4, mode: OUTPUT, id: relay_pin_1 }]